/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tyler' at '11/3/16 7:23 PM' with Gradle 2.13
 *
 * @author Tyler, @date 11/3/16 7:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
